[env]
TERM = "xterm-256color"

[cursor]
style = "Block"

[window]
padding = { x = 10, y = 5 }
dynamic_padding = true

[scrolling]
history = 500

[font]
size = 14.0

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true
