[env]
TERM = "xterm-256color"

[cursor]
style = "Block"

[window]
padding = { x = 10, y = 5 }
dynamic_padding = true

[scrolling]
history = 500

[font]
size = 16.0
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true
