-- [DARK VARIANT]
-- vim.api.nvim_set_hl(0, "Comment", { fg = "#FCE094", italic = true })
-- vim.api.nvim_set_hl(0, "Comment", { fg = "#5C6773", italic = true })
-- vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = "#14161b" })
-- vim.api.nvim_set_hl(0, "CursorLine", { bg = "#1c1d23" })
-- vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#4f5258" })
-- vim.api.nvim_set_hl(0, "MsgArea", { fg = "#2c2e33" })
-- vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#FCE094" })
-- vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#2c2e33" })
-- vim.api.nvim_set_hl(0, "LineNr", { fg = "#2c2e33" })
-- vim.api.nvim_set_hl(0, "DiagnosticError", { bg = "#1c1d23" })
-- vim.api.nvim_set_hl(0, "DiagnosticWarn", { bg = "#1c1d23" })
-- vim.api.nvim_set_hl(0, "DiagnosticInfo", { bg = "#1c1d23" })
-- vim.api.nvim_set_hl(0, "DiagnosticHint", { bg = "#1c1d23" })
-- vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { bg = "#1c1d23", fg = "#2C2E33" })
-- vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { bg = "#1c1d23", fg = "#FFB454" })
-- vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { bg = "#1c1d23", fg = "#A3D9FF" })
-- vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { bg = "#1c1d23", fg = "#2C2E33" })
-- vim.api.nvim_set_hl(0, "SignColumn", { fg = "#2c2e33", bg = "#1c1d23" })

-- [LIGHT VARIANT]
-- vim.api.nvim_set_hl(0, "Comment", { fg = "#FCE094", italic = true })
vim.api.nvim_set_hl(0, "Comment", { fg = "#9b9ea4", italic = true })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = "#e0e2ea" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#eef1f8" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#4f5258" })
vim.api.nvim_set_hl(0, "MsgArea", { fg = "#9b9ea4" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#14161b" })
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#2c2e33" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#9b9ea4" })
vim.api.nvim_set_hl(0, "DiagnosticError", { bg = "#c4c6cd" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { bg = "#c4c6cd" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { bg = "#c4c6cd" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { bg = "#c4c6cd" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { bg = "#c4c6cd", fg = "#2C2E33" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { bg = "#c4c6cd", fg = "#FFB454" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { bg = "#c4c6cd", fg = "#A3D9FF" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { bg = "#c4c6cd", fg = "#2C2E33" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#ffcaff" })
