-- my variations to the new neovim default colorscheme
vim.api.nvim_set_hl(0, "Comment", { fg = "#FCE094" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = "#14161b" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#1c1d23" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#4f5258" })
vim.api.nvim_set_hl(0, "MsgArea", { fg = "#2c2e33" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#FFCAFF" })
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#2c2e33" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#2c2e33" })
vim.api.nvim_set_hl(0, "DiagnosticError", { bg = "#1c1d23" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { bg = "#1c1d23" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { bg = "#1c1d23" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { bg = "#1c1d23" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { fg = "#4f5258" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { fg = "#4f5258" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { fg = "#4f5258" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { fg = "#4f5258" })
