[theme]
name   = "sage"         # matches your tmux/neovim aesthetic
parent = ""             # no inheritance, complete theme

[colors]                # Meaning → colour
Base       = "#1A1A1A"  # default foreground (near black)
Title      = "#6B7D6A"  # headers & section titles (sage green)
Important  = "#5F8A5F"  # success / good news (darker green)
Guidance   = "#9FA89E"  # hints & helper text (muted green-gray)
Annotation = "#B8B2A8"  # low-priority notes (light gray)
AlertInfo  = "#6B7D6A"  # neutral informational alerts (sage)
AlertWarn  = "#D97700"  # cautions (dimmed orange)
AlertError = "#FF4444"  # errors & critical alerts (vibrant red)
